[package]
name = "packagemanager"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
indicatif = "0.17.8"
serde = { version = "1.0.204", features = ["derive"] }
serde_yaml = "0.9.34"
